# Generated by Django 6.0.5 on 2026-05-11 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('shop', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('HIGH_REASONING', 'High Reasoning'), ('MID_REASONING', 'Mid Reasoning'), ('FAST_EXECUTION', 'Fast Execution')], max_length=20)),
                ('model_override', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter_pokemon', models.CharField(max_length=50)),
                ('partner_pokemon', models.CharField(max_length=50)),
                ('quiz_nature', models.CharField(max_length=20)),
                ('sprite', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('orchestrator', 'Orchestrator'), ('agent', 'Agent')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.agent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.session')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sleeping', 'Sleeping'), ('awake', 'Awake'), ('thinking', 'Thinking'), ('done', 'Done')], default='sleeping', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_agents', to='api.agent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_agents', to='api.session')),
            ],
            options={
                'unique_together': {('session', 'agent')},
            },
        ),
    ]
