# Generated by Django 6.0.5 on 2026-05-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_session_workspace_path_sessionsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='dex_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
