# Generated by Django 6.0.5 on 2026-05-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_agent_dex_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='partner_target',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='pending_plan',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='pending_step_index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
