# Generated by Django 6.0.5 on 2026-05-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_session_partner_target_session_pending_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionagent',
            name='status',
            field=models.CharField(choices=[('sleeping', 'Sleeping'), ('awake', 'Awake'), ('thinking', 'Thinking'), ('done', 'Done'), ('error', 'Error')], default='sleeping', max_length=20),
        ),
    ]
