# Generated by Django 6.0.4 on 2026-05-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('starter_pokemon', models.CharField(max_length=50)),
                ('partner_pokemon', models.CharField(max_length=50)),
                ('starter_nickname', models.CharField(blank=True, default='', max_length=50)),
                ('partner_nickname', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'game_engine_player_profile',
            },
        ),
    ]
